import SideBarUser from '@/components/SidebarUser/SideBarUser'

export const metadata = {
  title: 'Seu perfil',
  description: 'Generated by create next app',
}

export default function UserLayout({ children }) {
  return (
    <div className='flex'>
        <div>
            <SideBarUser/>
        </div>
        <div className='w-full'>
            {children}
        </div>
    </div>
  )
}